spring.config.import=optional:file:.env[.properties]

spring.application.name=${SPRING_APPLICATION_NAME:organize_it_backend}
debug=${DEBUG:true}
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
spring.data.mongodb.database=${SPRING_DATA_MONGODB_DATABASE:organize-it-backend}
spring.security.user.name=${SPRING_SECURITY_USER_NAME}
spring.security.user.password=${SPRING_SECURITY_USER_PASSWORD}
